# Mapping between internal format and "Bat Migration Europe" metadata format.
# More info: https://bat-migration-europe.netlify.app
#
# Source code: https://github.com/cloudedbats/cloudedbats_postproc

pathToTadatridaD: /home/pi/Tadarida-D/install_rpi/TadaridaD

sourceDirList: 
  - /mnt/usb4tb/rec2022/se-o-1
  - /mnt/usb4tb/rec2022/wurb51
  - /mnt/usb4tb/rec2022/wurb52
  - /mnt/usb4tb/rec2022/wurb53

